# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateE <- function(etas, lambdas, sigmas, data, S_mat, pi, z_nk, hold_z, loglik) {
    invisible(.Call(`_chimeralclustering_updateE`, etas, lambdas, sigmas, data, S_mat, pi, z_nk, hold_z, loglik))
}

updateAllEtaP <- function(data, lambdas, sigmas, etas, alphas, z_nk) {
    invisible(.Call(`_chimeralclustering_updateAllEtaP`, data, lambdas, sigmas, etas, alphas, z_nk))
}

updateOneLambdaP <- function(p, data, S_mat, lambdas, sigmas, etas, alphas, gamma, pi) {
    invisible(.Call(`_chimeralclustering_updateOneLambdaP`, p, data, S_mat, lambdas, sigmas, etas, alphas, gamma, pi))
}

updateOneAlphaC <- function(c, data, S_mat, lambdas, sigmas, etas, alphas, gamma, pi, nr_maxit, nr_eps = 1e-16) {
    invisible(.Call(`_chimeralclustering_updateOneAlphaC`, c, data, S_mat, lambdas, sigmas, etas, alphas, gamma, pi, nr_maxit, nr_eps))
}

equilibriateAllAlphaC <- function(lambdas, sigmas, etas, alphas, eqb_tol = 1e-8) {
    invisible(.Call(`_chimeralclustering_equilibriateAllAlphaC`, lambdas, sigmas, etas, alphas, eqb_tol))
}

vech <- function(x) {
    .Call(`_chimeralclustering_vech`, x)
}

updateLambdaC <- function(lambdas, sigmas, alphas) {
    invisible(.Call(`_chimeralclustering_updateLambdaC`, lambdas, sigmas, alphas))
}

updateEtaC <- function(etas, alphas) {
    invisible(.Call(`_chimeralclustering_updateEtaC`, etas, alphas))
}

parameterVector <- function(etas, lambdas, alphas, pi, data) {
    .Call(`_chimeralclustering_parameterVector`, etas, lambdas, alphas, pi, data)
}

runEM <- function(niter, state, nr_maxit = 1L, nr_eps = 1e-16, holdziters = 0L, show_progress = TRUE) {
    .Call(`_chimeralclustering_runEM`, niter, state, nr_maxit, nr_eps, holdziters, show_progress)
}

